export const CATEGORIES = [
  "FRUTAS",
  "VERDURAS Y HORTALIZAS",
  "PULPAS",
  "VARIOS",
  "CARNES X 500 GRAMOS",
  "CONDIMENTOS X 125 GR",
  "FRUTOS SECOS Y ESPECIAS",
  "AROMÁTICAS Y HIERBAS X 125 GR",
  "KITS NEGOCIOS"
];

export const SUBCATEGORIES: Record<string, string[]> = {
  "CARNES X 500 GRAMOS": ["CARNE DE RES", "CARNE DE CERDO", "VÍSCERAS", "POLLO", "PESCADO"],
};
